"""initial_schema

Revision ID: 12adda5d4a45
Revises:
Create Date: 2026-08-11 21:46:09.036187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '12adda5d4a45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organizer', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_finds',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('species_name', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('contributor_name', sa.String(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forage_clubs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_url', sa.String(), nullable=True),
    sa.Column('meeting_cadence', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate_limit_events',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_action_key_created', 'rate_limit_events', ['action', 'key_hash', 'created_at'], unique=False)
    op.create_table('resource_guides',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('latin_name', sa.String(), nullable=False),
    sa.Column('edibility', sa.String(), nullable=True),
    sa.Column('look_alikes', sa.Text(), nullable=True),
    sa.Column('habitat_notes', sa.Text(), nullable=True),
    sa.Column('peak_months', sa.String(), nullable=True),
    sa.Column('elevation_min_ft', sa.Integer(), nullable=True),
    sa.Column('elevation_max_ft', sa.Integer(), nullable=True),
    sa.Column('utah_regions', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('total_finds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('account_tokens',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_tokens_token_hash'), 'account_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_account_tokens_user_id'), 'account_tokens', ['user_id'], unique=False)
    op.create_table('sightings',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('species_id', app.models.GUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('elevation_ft', sa.Float(), nullable=True),
    sa.Column('found_on', sa.Date(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('habitat_type', sa.String(), nullable=True),
    sa.Column('substrate', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('location_privacy', sa.String(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_id', app.models.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('crawled_sources',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('sighting_id', app.models.GUID(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('saved_locations',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_id', app.models.GUID(), nullable=False),
    sa.Column('sighting_id', app.models.GUID(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_locations_user_id'), 'saved_locations', ['user_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('sighting_id', app.models.GUID(), nullable=False),
    sa.Column('verifier_id', app.models.GUID(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sighting_id'], ['sightings.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_index(op.f('ix_saved_locations_user_id'), table_name='saved_locations')
    op.drop_table('saved_locations')
    op.drop_table('crawled_sources')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('sightings')
    op.drop_index(op.f('ix_account_tokens_user_id'), table_name='account_tokens')
    op.drop_index(op.f('ix_account_tokens_token_hash'), table_name='account_tokens')
    op.drop_table('account_tokens')
    op.drop_table('users')
    op.drop_table('species')
    op.drop_table('resource_guides')
    op.drop_index('ix_rate_limit_action_key_created', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    op.drop_table('forage_clubs')
    op.drop_table('community_finds')
    op.drop_table('community_events')
    # ### end Alembic commands ###
