"""Reference catalogue shared by the seeder.

Months are a northern-hemisphere reference. Southern-hemisphere fruiting for the
same species is generally offset by about six months, so the map filters on the
month recorded with each observation rather than on this catalogue.

Elevations are stored in feet because that is the storage unit of the database;
the interface converts to metres for readers who prefer metric units.
"""

GLOBAL_FUNGI = [
    {
        "common_name": "Morel",
        "latin_name": "Morchella spp.",
        "edibility": "choice",
        "look_alikes": "False morels (Gyromitra species) can be toxic; true morels are hollow from cap to stem base.",
        "habitat_notes": "Disturbed ground, recent burn scars, riverside hardwoods, and old orchards.",
        "peak_months": "3,4,5,6",
        "elevation_min_ft": 0,
        "elevation_max_ft": 11000,
        "regions": "Temperate Europe, North America, Turkey, Himalaya, East Asia; introduced in Australasia",
        "notes": "Fruits as soils warm after spring moisture. Always cook thoroughly.",
    },
    {
        "common_name": "King Bolete",
        "latin_name": "Boletus edulis group",
        "edibility": "choice",
        "look_alikes": "Bitter bolete and red-pored boletes; several bolete groups are regional and unresolved.",
        "habitat_notes": "Mycorrhizal with spruce, fir, pine, oak, and beech.",
        "peak_months": "7,8,9,10",
        "elevation_min_ft": 0,
        "elevation_max_ft": 12000,
        "regions": "Europe, northern Asia, North America; introduced with pine plantations in New Zealand and southern Africa",
        "notes": "Flushes after sustained rain and cool nights.",
    },
    {
        "common_name": "Golden Chanterelle",
        "latin_name": "Cantharellus cibarius group",
        "edibility": "choice",
        "look_alikes": "False chanterelle and jack-o'-lantern mushrooms, which are toxic.",
        "habitat_notes": "Mossy conifer and broadleaf forest, often on slopes and along old tracks.",
        "peak_months": "6,7,8,9,10",
        "elevation_min_ft": 0,
        "elevation_max_ft": 10000,
        "regions": "Europe, North America, East Asia, and montane Africa",
        "notes": "Look for blunt forked ridges running down the stem rather than blade-like gills.",
    },
    {
        "common_name": "Oyster Mushroom",
        "latin_name": "Pleurotus ostreatus group",
        "edibility": "edible",
        "look_alikes": "Angel wings and other pale shelf fungi on wood.",
        "habitat_notes": "Shelving clusters on dead or declining broadleaf trees.",
        "peak_months": "3,4,5,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Worldwide in temperate and subtropical forest",
        "notes": "Confirm the host wood, decurrent gills, and spore print colour.",
    },
    {
        "common_name": "Shaggy Ink Cap",
        "latin_name": "Coprinus comatus",
        "edibility": "edible",
        "look_alikes": "Other ink caps, some of which react badly with alcohol.",
        "habitat_notes": "Lawns, verges, playing fields, and compacted disturbed soil.",
        "peak_months": "4,5,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Worldwide in temperate grassland and urban ground",
        "notes": "Dissolves into ink within a day; document soon after emergence.",
    },
    {
        "common_name": "Field Mushroom",
        "latin_name": "Agaricus campestris",
        "edibility": "edible",
        "look_alikes": "Young Amanita species and the toxic yellow-staining mushroom.",
        "habitat_notes": "Unimproved pasture, meadows, and grazed grassland.",
        "peak_months": "5,6,9,10",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Worldwide in temperate grassland",
        "notes": "Check for pink to brown gills and the absence of a basal cup.",
    },
    {
        "common_name": "Giant Puffball",
        "latin_name": "Calvatia gigantea",
        "edibility": "edible",
        "look_alikes": "Earthballs and immature Amanita buttons.",
        "habitat_notes": "Meadows, hedgerows, and nutrient-rich pasture.",
        "peak_months": "7,8,9,10",
        "elevation_min_ft": 0,
        "elevation_max_ft": 8000,
        "regions": "Temperate Europe, North America, and northern Asia",
        "notes": "Cut every specimen vertically; the interior must be uniform white with no internal mushroom outline.",
    },
    {
        "common_name": "Hedgehog Mushroom",
        "latin_name": "Hydnum repandum",
        "edibility": "edible",
        "look_alikes": "Other toothed fungi, none of which are seriously toxic in this habitat.",
        "habitat_notes": "Mossy conifer and mixed forest floor.",
        "peak_months": "8,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 10000,
        "regions": "Europe, North America, and East Asia",
        "notes": "The underside carries soft spines instead of gills or pores.",
    },
    {
        "common_name": "Lion's Mane",
        "latin_name": "Hericium erinaceus",
        "edibility": "edible",
        "look_alikes": "Other Hericium species, which are also edible.",
        "habitat_notes": "Wounds and dead sections of standing broadleaf trees.",
        "peak_months": "8,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 8500,
        "regions": "Temperate North America, Europe, and East Asia",
        "notes": "Protected or red-listed in parts of Europe; check local rules before collecting.",
    },
    {
        "common_name": "Wood Ear",
        "latin_name": "Auricularia auricula-judae group",
        "edibility": "edible",
        "look_alikes": "Few; other jelly fungi are broadly harmless but differ in texture.",
        "habitat_notes": "Damp dead wood, especially elder and other soft broadleaf timber.",
        "peak_months": "1,2,3,10,11,12",
        "elevation_min_ft": 0,
        "elevation_max_ft": 8000,
        "regions": "Worldwide, including tropical Asia, Africa, and the Americas",
        "notes": "One of the few groups that fruits through mild winters.",
    },
    {
        "common_name": "Saffron Milkcap",
        "latin_name": "Lactarius deliciosus",
        "edibility": "edible",
        "look_alikes": "Other Lactarius species; this group bleeds orange and stains green.",
        "habitat_notes": "Pine forest and pine plantations, often in needle litter.",
        "peak_months": "9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Europe and Asia; established with planted pines in Chile, Argentina, Australia, New Zealand, and southern Africa",
        "notes": "In the southern hemisphere the main flush falls between March and June.",
    },
    {
        "common_name": "Slippery Jack",
        "latin_name": "Suillus luteus",
        "edibility": "edible",
        "look_alikes": "Other Suillus species, which are similar and broadly edible.",
        "habitat_notes": "Two-needle pines, including plantation pine.",
        "peak_months": "9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9500,
        "regions": "Europe and Asia; widely introduced with pines across South America, Australasia, and southern Africa",
        "notes": "Peel the slimy cap skin; it upsets some people.",
    },
    {
        "common_name": "Termite Mushroom",
        "latin_name": "Termitomyces spp.",
        "edibility": "edible",
        "look_alikes": "Pale Amanita and Chlorophyllum species growing on the same ground.",
        "habitat_notes": "Grows from termite nests in savanna, farmland, and open woodland.",
        "peak_months": "5,6,11,12",
        "elevation_min_ft": 0,
        "elevation_max_ft": 7000,
        "regions": "Sub-Saharan Africa, South Asia, and Southeast Asia",
        "notes": "Fruits with the local rains; harvest customs and land rights vary strongly by community.",
    },
    {
        "common_name": "Cauliflower Mushroom",
        "latin_name": "Sparassis crispa",
        "edibility": "edible",
        "look_alikes": "Other Sparassis species, which are also edible.",
        "habitat_notes": "Base of living or recently dead conifers, especially pine.",
        "peak_months": "8,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Europe, North America, and East Asia",
        "notes": "Grit collects deep in the folds; document the host tree.",
    },
    {
        "common_name": "Fly Agaric",
        "latin_name": "Amanita muscaria",
        "edibility": "poisonous",
        "look_alikes": "Other Amanita species, including deadly ones.",
        "habitat_notes": "Birch, pine, and spruce, and planted conifers far outside the native range.",
        "peak_months": "8,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 11000,
        "regions": "Circumboreal; introduced across Australia, New Zealand, South America, and southern Africa",
        "notes": "Mapped as a habitat and safety marker, not as a forage recommendation.",
    },
    {
        "common_name": "Death Cap",
        "latin_name": "Amanita phalloides",
        "edibility": "deadly",
        "look_alikes": "Paddy straw mushroom, young field mushrooms, and edible Amanita species.",
        "habitat_notes": "Oak, chestnut, beech, and planted urban trees.",
        "peak_months": "8,9,10,11,12",
        "elevation_min_ft": 0,
        "elevation_max_ft": 7500,
        "regions": "Native to Europe; invasive in North America, Australia, South America, and southern Africa",
        "notes": "Responsible for most fatal mushroom poisonings worldwide. Never taste an unknown white-gilled mushroom.",
    },
    {
        "common_name": "Destroying Angel",
        "latin_name": "Amanita virosa group",
        "edibility": "deadly",
        "look_alikes": "White field mushrooms and puffball buttons.",
        "habitat_notes": "Woodland soil near mycorrhizal host trees.",
        "peak_months": "7,8,9,10",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9500,
        "regions": "Temperate Europe, Asia, and North America",
        "notes": "Potentially fatal. Look for a basal cup, white gills, and a ring.",
    },
    {
        "common_name": "Green-spored Parasol",
        "latin_name": "Chlorophyllum molybdites",
        "edibility": "poisonous",
        "look_alikes": "Shaggy parasol and other edible parasols.",
        "habitat_notes": "Lawns, parks, and irrigated grass in warm climates.",
        "peak_months": "5,6,7,8,9",
        "elevation_min_ft": 0,
        "elevation_max_ft": 8000,
        "regions": "Subtropical and tropical worldwide, including the Americas, Africa, South Asia, and Australia",
        "notes": "The most frequently eaten poisonous mushroom in many warm regions. Take a spore print: it is green.",
    },
    {
        "common_name": "False Morel",
        "latin_name": "Gyromitra esculenta",
        "edibility": "poisonous",
        "look_alikes": "True morels.",
        "habitat_notes": "Conifer forest and disturbed sandy ground in spring.",
        "peak_months": "3,4,5,6",
        "elevation_min_ft": 0,
        "elevation_max_ft": 9000,
        "regions": "Temperate Europe, Asia, and North America",
        "notes": "Contains gyromitrin. The interior is chambered and the cap is brain-like rather than pitted.",
    },
    {
        "common_name": "Jack-o'-lantern",
        "latin_name": "Omphalotus spp.",
        "edibility": "poisonous",
        "look_alikes": "Chanterelles.",
        "habitat_notes": "Clustered at the base of stumps and buried broadleaf roots.",
        "peak_months": "7,8,9,10,11",
        "elevation_min_ft": 0,
        "elevation_max_ft": 7500,
        "regions": "Europe, North America, East Asia, and Australia",
        "notes": "True gills, growth on wood, and a clustered habit separate it from chanterelles.",
    },
]


# (common_name, latitude, longitude, elevation_ft, habitat, month, place_name)
SEED_SIGHTINGS = [
    ("Morel", 48.052, 7.048, 2300, "forest", 4, "Grand Est, France"),
    ("Morel", 44.351, -121.902, 4300, "forest", 5, "Oregon, United States"),
    ("King Bolete", 47.851, 11.354, 2100, "forest", 9, "Bavaria, Germany"),
    ("Golden Chanterelle", 59.352, 15.204, 310, "forest", 8, "Orebro, Sweden"),
    ("Oyster Mushroom", 35.652, 138.601, 2600, "forest", 11, "Yamanashi, Japan"),
    ("Shaggy Ink Cap", 51.503, -0.142, 90, "urban", 10, "London, United Kingdom"),
    ("Giant Puffball", 52.212, 21.017, 330, "meadow", 9, "Masovia, Poland"),
    ("Saffron Milkcap", -39.281, -72.203, 1200, "forest", 4, "Araucania, Chile"),
    ("Slippery Jack", -41.104, 175.043, 900, "forest", 5, "Wellington, New Zealand"),
    ("Field Mushroom", -33.873, 151.008, 130, "grassland", 5, "New South Wales, Australia"),
    ("Termite Mushroom", -6.812, 37.663, 1700, "grassland", 12, "Morogoro, Tanzania"),
    ("Wood Ear", 10.302, -84.807, 2000, "rainforest", 9, "Alajuela, Costa Rica"),
    ("Fly Agaric", 49.301, -123.117, 300, "forest", 10, "British Columbia, Canada"),
    ("Death Cap", 37.902, -122.301, 200, "urban", 12, "California, United States"),
    ("Green-spored Parasol", 12.972, 77.594, 3000, "grassland", 7, "Karnataka, India"),
]


COMMUNITY_FINDS = [
    {
        "title": "Spring morels along a Vosges river terrace",
        "region": "Europe",
        "species_name": "Morel",
        "summary": "A reviewed field note from ash and poplar terrace soil after two warm weeks.",
        "contributor_name": "Community scout",
        "reviewed": True,
    },
    {
        "title": "Autumn boletes in Bavarian spruce",
        "region": "Europe",
        "species_name": "King Bolete",
        "summary": "Several firm boletes recorded after sustained rain and cool nights.",
        "contributor_name": "iNaturalist import",
        "reviewed": True,
    },
    {
        "title": "Saffron milkcaps in a Patagonian pine plantation",
        "region": "South America",
        "species_name": "Saffron Milkcap",
        "summary": "A southern-hemisphere autumn flush, six months out of step with European records.",
        "contributor_name": "Community scout",
        "reviewed": True,
    },
    {
        "title": "Termite mushrooms after the first heavy rains",
        "region": "Africa",
        "species_name": "Termite Mushroom",
        "summary": "Documented on farmland margins; collecting here follows local custom and landholder permission.",
        "contributor_name": "Community scout",
        "reviewed": False,
    },
]


COMMUNITY_EVENTS = [
    {
        "title": "Beginner identification walk",
        "days_ahead": 21,
        "location_name": "Epping Forest, London",
        "region": "Europe",
        "description": "A leave-no-trace walk focused on habitat, field marks, and recording practice.",
        "organizer": "Volunteer field desk",
    },
    {
        "title": "Autumn foray and identification table",
        "days_ahead": 35,
        "location_name": "Dandenong Ranges, Victoria",
        "region": "Oceania",
        "description": "Southern-hemisphere autumn survey with an identification table afterwards.",
        "organizer": "Volunteer survey team",
    },
    {
        "title": "Monsoon fungi survey",
        "days_ahead": 52,
        "location_name": "Western Ghats, Karnataka",
        "region": "Asia",
        "description": "Document substrate, elevation, and weather during the wet season flush.",
        "organizer": "Regional survey volunteers",
    },
]


FORAGE_CLUBS = [
    {
        "name": "North American Mycological Association",
        "region": "North America",
        "description": "Affiliated clubs, forays, and identification resources across the United States and Canada.",
        "contact_url": "https://namyco.org",
        "meeting_cadence": "Local clubs meet year round",
    },
    {
        "name": "Association of British Fungus Groups",
        "region": "Europe",
        "description": "Recording groups, forays, and identification support across Britain and Ireland.",
        "contact_url": "https://www.abfg.org",
        "meeting_cadence": "Seasonal forays",
    },
    {
        "name": "Fungimap",
        "region": "Oceania",
        "description": "Citizen-science fungal recording and conservation across Australia.",
        "contact_url": "https://fungimap.org.au",
        "meeting_cadence": "Seasonal projects",
    },
    {
        "name": "Fungi Foundation",
        "region": "Global",
        "description": "Fungal conservation, education, and policy work with programmes on several continents.",
        "contact_url": "https://ffungi.org",
        "meeting_cadence": "Ongoing programmes",
    },
    {
        "name": "Fungal Diversity Survey",
        "region": "North America",
        "description": "Community documentation projects that turn field observations into vouchered records.",
        "contact_url": "https://fundis.org",
        "meeting_cadence": "Rolling projects",
    },
]


RESOURCE_GUIDES = [
    {
        "title": "Find your regional poison centre",
        "category": "Safety",
        "summary": "Keep the number for your country's poison centre saved before you go out.",
        "url": "https://www.who.int/publications/m/item/world-directory-of-poisons-centres",
        "priority": 1,
    },
    {
        "title": "Deadly look-alikes to learn first",
        "category": "Safety",
        "summary": "Death cap, destroying angel, false morel, and the green-spored parasol cover most serious poisonings worldwide.",
        "priority": 10,
    },
    {
        "title": "Check collecting rules where you are",
        "category": "Access",
        "summary": "Rules differ by country, protected area, and landholder. Some species are protected even where collecting is allowed.",
        "priority": 20,
    },
    {
        "title": "Seasons north and south",
        "category": "Guide",
        "summary": "Fruiting windows shift by roughly six months between hemispheres and track local rainfall in the tropics.",
        "priority": 30,
    },
    {
        "title": "How to submit useful field notes",
        "category": "Community",
        "summary": "Photo angles, substrate, host tree, weather, elevation, and location precision that help reviewers.",
        "priority": 40,
    },
    {
        "title": "Sharing locations responsibly",
        "category": "Community",
        "summary": "Public points are shifted from the exact find. Keep sensitive or protected sites private.",
        "priority": 50,
    },
]
