UTAH_FUNGI = [
    {
        "common_name": "Morel",
        "latin_name": "Morchella spp.",
        "edibility": "choice",
        "look_alikes": "False morels can be toxic; verify hollow stems and caps.",
        "habitat_notes": "Cottonwood bottoms, recent burn scars, and disturbed mountain soils.",
        "peak_months": "4,5,6",
        "elevation_min_ft": 4500,
        "elevation_max_ft": 8500,
        "utah_regions": "Wasatch, Uintas, Cache Valley, central mountains",
        "notes": "Often follows spring moisture and warming soil.",
    },
    {
        "common_name": "King Bolete",
        "latin_name": "Boletus edulis group",
        "edibility": "choice",
        "look_alikes": "Avoid bitter boletes and red-pored boletes unless expert-confirmed.",
        "habitat_notes": "High-elevation conifer forests, especially spruce and fir.",
        "peak_months": "7,8,9",
        "elevation_min_ft": 7500,
        "elevation_max_ft": 11000,
        "utah_regions": "Uintas, Wasatch Plateau, Boulder Mountain",
        "notes": "Flushes after monsoon storms in cool conifer habitat.",
    },
    {
        "common_name": "Oyster Mushroom",
        "latin_name": "Pleurotus ostreatus group",
        "edibility": "edible",
        "look_alikes": "Compare carefully with angel wings and other white shelf fungi.",
        "habitat_notes": "Dead or dying hardwoods in canyons and riparian corridors.",
        "peak_months": "4,5,9,10,11",
        "elevation_min_ft": 4000,
        "elevation_max_ft": 9000,
        "utah_regions": "Wasatch canyons, riparian corridors statewide",
        "notes": "Usually grows in shelves or clusters on wood.",
    },
    {
        "common_name": "Shaggy Mane",
        "latin_name": "Coprinus comatus",
        "edibility": "edible",
        "look_alikes": "Ink caps can be confusing; collect young white specimens only.",
        "habitat_notes": "Lawns, parks, roadsides, trail edges, and compacted soil.",
        "peak_months": "5,6,9,10",
        "elevation_min_ft": 4000,
        "elevation_max_ft": 8500,
        "utah_regions": "Urban Wasatch Front, mountain valleys",
        "notes": "Deliquesces quickly; best documented soon after emergence.",
    },
    {
        "common_name": "Fly Agaric",
        "latin_name": "Amanita muscaria group",
        "edibility": "poisonous",
        "look_alikes": "Amanitas include deadly species; do not eat.",
        "habitat_notes": "Conifer and mixed forests, often near spruce, fir, or birch.",
        "peak_months": "7,8,9,10",
        "elevation_min_ft": 6500,
        "elevation_max_ft": 10500,
        "utah_regions": "Uintas, Wasatch, high plateaus",
        "notes": "Included as a safety-relevant map layer, not a forage recommendation.",
    },
]


SEED_SIGHTINGS = [
    {
        "species_latin_name": "Morchella spp.",
        "latitude": 40.5721,
        "longitude": -111.6518,
        "elevation_ft": 7350,
        "found_on": "2026-05-23",
        "habitat_type": "forest",
        "substrate": "burn scar duff",
        "notes": "Small cluster near aspen edge after several warm days.",
        "source": "community",
        "confidence_score": 72,
        "verified": True,
    },
    {
        "species_latin_name": "Boletus edulis group",
        "latitude": 40.7164,
        "longitude": -110.8739,
        "elevation_ft": 9450,
        "found_on": "2026-08-02",
        "habitat_type": "forest",
        "substrate": "spruce needle litter",
        "notes": "Documented during a wet monsoon week.",
        "source": "iNaturalist",
        "confidence_score": 84,
        "verified": True,
    },
    {
        "species_latin_name": "Pleurotus ostreatus group",
        "latitude": 40.645,
        "longitude": -111.4833,
        "elevation_ft": 6400,
        "found_on": "2026-10-08",
        "habitat_type": "riparian",
        "substrate": "downed cottonwood",
        "notes": "Shelf growth on shaded creekside log.",
        "source": "GBIF",
        "confidence_score": 68,
        "verified": False,
    },
    {
        "species_latin_name": "Coprinus comatus",
        "latitude": 40.7608,
        "longitude": -111.891,
        "elevation_ft": 4265,
        "found_on": "2026-09-16",
        "habitat_type": "meadow",
        "substrate": "irrigated turf",
        "notes": "Young fruiting bodies along a park path.",
        "source": "community",
        "confidence_score": 58,
        "verified": False,
    },
    {
        "species_latin_name": "Amanita muscaria group",
        "latitude": 39.1006,
        "longitude": -111.4801,
        "elevation_ft": 8850,
        "found_on": "2026-08-29",
        "habitat_type": "forest",
        "substrate": "mixed conifer duff",
        "notes": "Safety sighting: poisonous amanita in popular camping area.",
        "source": "iNaturalist",
        "confidence_score": 79,
        "verified": True,
    },
]


COMMUNITY_FINDS = [
    {
        "title": "Burn-scar morels after spring rain",
        "region": "Wasatch",
        "species_name": "Morel",
        "summary": "Reviewed field note from an aspen edge near a recent burn scar.",
        "contributor_name": "Community scout",
        "reviewed": True,
    },
    {
        "title": "High Uinta bolete flush",
        "region": "Uintas",
        "species_name": "King Bolete",
        "summary": "Several firm boletes documented after monsoon storms in spruce-fir habitat.",
        "contributor_name": "iNaturalist import",
        "reviewed": True,
    },
    {
        "title": "Cottonwood oysters in shaded canyon",
        "region": "Wasatch canyons",
        "species_name": "Oyster Mushroom",
        "summary": "Shelf growth on downed cottonwood, pending a better underside photo.",
        "contributor_name": "GBIF import",
        "reviewed": False,
    },
]


COMMUNITY_EVENTS = [
    {
        "title": "Monsoon mushroom walk",
        "starts_on": "2026-08-24",
        "location_name": "Mirror Lake Highway",
        "region": "Uintas",
        "description": "A beginner-friendly walk focused on high-elevation habitat and field documentation.",
        "organizer": "Utah Forage Map volunteers",
    },
    {
        "title": "Beginner ID table",
        "starts_on": "2026-09-07",
        "location_name": "Salt Lake City",
        "region": "Wasatch Front",
        "description": "Bring photos, spore prints, and notes for a community review session.",
        "organizer": "Salt Lake field mycology group",
    },
    {
        "title": "Fall canyon survey",
        "starts_on": "2026-10-12",
        "location_name": "Big Cottonwood",
        "region": "Wasatch",
        "description": "Document late-season fruiting around riparian corridors and mixed conifer stands.",
        "organizer": "Utah Forage Map volunteers",
    },
]


FORAGE_CLUBS = [
    {
        "name": "Salt Lake Field Mycology",
        "region": "Wasatch Front",
        "description": "Meetups, ID tables, and beginner walks around northern Utah.",
        "meeting_cadence": "Monthly during peak season",
    },
    {
        "name": "Uinta High Country Survey",
        "region": "Uintas",
        "description": "Volunteer group documenting high-elevation boletes, amanitas, and habitat notes.",
        "meeting_cadence": "Seasonal surveys",
    },
    {
        "name": "Southern Utah Fungi Watch",
        "region": "Southern Utah",
        "description": "Dryland and canyon-focused observations with extra emphasis on safety and access rules.",
        "meeting_cadence": "Quarterly",
    },
]


RESOURCE_GUIDES = [
    {
        "title": "Utah collecting rules by land type",
        "category": "Access",
        "summary": "Check rules for national forests, state parks, BLM parcels, private land, and protected areas.",
        "priority": 10,
    },
    {
        "title": "Poisonous look-alikes checklist",
        "category": "Safety",
        "summary": "A field-first reminder to verify multiple traits before considering edibility.",
        "priority": 20,
    },
    {
        "title": "Season and elevation field guide",
        "category": "Guide",
        "summary": "Typical Utah fruiting windows by mushroom group, elevation band, and habitat.",
        "priority": 30,
    },
    {
        "title": "How to submit useful field notes",
        "category": "Community",
        "summary": "Photo angles, substrate, weather, GPS precision, and habitat details that help reviewers.",
        "priority": 40,
    },
]
